Development
Divinity-dev/Recipe-App pull request #17
Opened 2023-06-02 18:01 UTC by Divinity-dev

In this project, we have implemented the following;

- [ ] A login page.
- [ ] A registration page.
- [ ] A food list (with all CRUD implementation, except for 'update').
- [ ] A recipes list (with all CRUD implementation, except for 'update').
- [ ] A general shopping list view (all missing food for all your recipes and total price).
- [ ] A list of all public recipes from other users with their names and total prices.

2023-06-02 21:58 UTC, DeliceLydia commented
### Hi Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that has `node_modules` on the repo and the file is heavy I can't review it please add it in the `gitignore`

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

### Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2023-06-03 01:08 UTC, fobadara requested changes
Hi team, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

## Highlights
✅ All tests are passing
✅ Clean code
✅ Good first attempt

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-03 01:08 UTC, fobadara commented on config/routes.rb
> +  resources :shopping_list
[REQUIRED] I noticed that you have only the index endpoint for the shopping_list controller yet you are not excluding it from your routes. Kindly remove it since there is no point wasting resources. Kindly remove it since there is no point wasting resources. You can use :except or :only with resources to fix it

2023-06-03 01:08 UTC, fobadara commented on config/routes.rb
> +  resources :public_recipes
[REQUIRED] I noticed that you have only the index endpoint for the public_recipes controller yet you are not excluding it from your routes. Kindly remove it since there is no point wasting resources. Kindly remove it since there is no point wasting resources. You can use :except or :only with resources to fix it

2023-06-03 01:08 UTC, fobadara requested changes
Hi team, 

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

## Highlights
✅ All tests are passing
✅ Clean code
✅ Good first attempt

## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-06-03 05:45 UTC, Divinity-dev commented
Thanks for the review
    On Saturday, June 3, 2023 at 02:08:48 AM GMT+1, Abdulfatai Badara ***@***.***> wrote:  
 
 


@fobadara requested changes on this pull request.

Hi team,

Good job so far!
You still need to work on some issues to go to the next project, but you are almost there!

Highlights

 ✅ All tests are passing
 ✅ Clean code
 ✅ Good first attempt

Required Changes ♻️
 
Check the comments under the review.

Optional suggestions

Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better.

Cheers, and Happy coding! 👏 👏 👏
 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.

As described in the Code reviews limits policy you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this form.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***>

2023-06-03 06:22 UTC, Ismailco approved these changes
### Hi @Divinity-dev, 

In my opinion, your project is ready for the presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![cr-approve](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)

## Highlights

✔️ Good communication
✔️  No linter errors
✔️ Used Gitflow
✔️ Work documented professionally

Good luck! 🎉 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

2023-06-03 06:26 UTC, Divinity-dev commented
Thank you very much 

Sent from Yahoo Mail on Android 
 
  On Sat, Jun 3, 2023 at 7:23 AM, ismail ***@***.***> wrote:   


@Ismailco approved this pull request.

Hi @Divinity-dev,

In my opinion, your project is ready for the presentation! There is nothing else to say other than... it's time to merge it 



Highlights

 ✔️ Good communication
 ✔️ No linter errors
 ✔️ Used Gitflow
 ✔️ Work documented professionally

Good luck! 🎉
 
Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2023-06-03 16:38 UTC, merged